### ISSUE TITLE
deleting feature branches maps, events page?

### ISSUE THREAD

**Issue by christoball** [TNRIS/tnris.org#102]
What's the protocol for deleting feature branches? Can anyone delete once we're done or should the branch creator? 

Just looking to keep stuff cleaned up.

**Comment by christoball** [comment]
I went ahead and deleted the events circle size branch since i was helpign with that.

**Comment by adambreznicky** [comment]
right on, keeping stuff clean is always awesome!

if a PR comes in from a 'feature' branch (i.e. not develop or one of the barbwire branches), i delete the branch after approving and merging since that code is now on one of our permanent branches. i think, in general, if you see a feature or one-off branch hanging out that is no longer being used or wasn't deleted after merging then it is safe to just go ahead and delete it. 

i think it is standard practice for the PR reviewer to delete the branch at the time of approving it.

**Comment by christoball** [comment]
@adambreznicky thanks that makes sense, just want to be clear on protocol.
