### ISSUE TITLE
Order Historical Imagery Search by most recent 'Date'

### ISSUE THREAD

**Issue by christoball** [TNRIS/tnris.org#1125]
Currently, the historical imagery defaults to oldest date first. What do people think about switching this to have the most recent date at the top?

The other datasets are also ordered by most recent first.

@mitchellryant @adambreznicky @wilsaj

**Comment by adambreznicky** [comment]
i sorted by date in order from oldest to newest in order to match the year list which displays in the blurb.  i put it that way for consistency, thinking it would be more streamlined to what the user is expecting based on the info they got in the blurb.
we can change it if y'alls want. we can order it by default to any of those fields, ascending or descending.

**Comment by christoball** [comment]
I'm personally ok with keeping the order starting with the earliest on the header but defaulting it to most recent on the table.

Note to self: add 'padding: 0 20%;' to '.panel-title h3'

**Comment by adambreznicky** [comment]
updated the sorting to start with the latest year and adding the padding as requested.
ref commit fb9bae1ff69542bacf06dc0a2397902f7fedf345
