### ISSUE TITLE
Add class to body tag

### ISSUE THREAD

**Issue by christoball** [TNRIS/tnris.org#138]
In addition to ID, add class generated from page name. Can be exact same as id in the class="" attribute

this would be to follow best css practices of not using id as selectors but still allow for individual page styling where needed

**Comment by wilsaj** [comment]
I don't think this is a good idea. The best practice of not using id selectors is to avoid one-off rule sets, which is exactly what individual page styling is. If there are one-off rule sets, then IDs at least make that clear upon reading the css. I'm also worried that auto-populating page name as a class could lead to inadvertent interactions if a page name conflicts with some other class in our rules. For example, if we ever make a page for tnris.org/media/, there's going to be some weird things going on because it will have the "media" class applied to it.

**Comment by christoball** [comment]
I hear you. I'm not opposed but if we want to achieve Lint perfection, can/should we remove that rule from the check?

It seems like the ID usage question is in debate. I think for usage like this, I've always considered it syntactical and appropriate, but I'm an eternal n00b :)
