### ISSUE TITLE
Bern Keynote Article

### ISSUE THREAD

**Issue by christoball** [TNRIS/tnris.org#1405]
Publish article to announce Keynote Bern Szukalski

**Comment by christoball** [comment]
Content provided by @KCMack:
Bern has witnessed the development of GIS from the mid-80’s when he began his geospatial career with Esri as an applications specialist. His abilities were quickly recognized providing him with opportunities to be involved in a broad spectrum of GIS implementation and software development projects.
Highlights of his career include authoring Esri’s first user call and bug tracking system, developing the first GUI for ARC/INFO (ArcTools), and teaching/promoting Avenue (scripting language for ArcView 2.0). Bern has also served as the product manager for MapObjects, MapObjects IMS, ArcIMS, ArcGIS Explorer Desktop, and ArcGIS Online. In addition to ArcGIS Online, he’s recently been involved with product management for the Living Atlas and Story Maps.
The depth of Bern’s professional experience and knowledge keep him in high demand for worldwide workshops and keynote engagements. As a product strategist and technical evangelist, he focuses on ways to broaden access to geographic information and GIS capabilities via the web. Through it all, he remains humble and entirely fascinated by the ever-evolving state of GIS and its capabilities to make a difference.
He's been known to say that on a good day he's making a map, and on a great day, he's on one.

Edit suggested by @pwblanton :
Just two edits: first line remove the comma in mid-80s, and in the second line add a comma after the word "recognized". Looks great!

**Comment by KCMack** [comment]
It's ready to go!

**Comment by christoball** [comment]
@KCMack @pwblanton please review. I added a short intro which can be changed however.

https://preview.tnris.org/ellwood/5fd435c505019d131c36c3238cc38943dc4ba9e2/news/2017-09-20/technical-evangelist-technology-advocate-forum-keynote-bern-szulkaski/

**Comment by KCMack** [comment]
Please check the spelling of Bern's last name.  I believe it is Szukalski.

I agree with the intro concept.

How about this:
Esri has played a key role in the Texas GIS Forum beginning in 1987 when Jack Dangermond, the founder of  Esri, was the  keynote speaker.  Every year since then Esri has showed up to support the conference as a primary sponsor.

This year we're proud to welcome Bern Szukalski, Esri's well known and highly regarded  technical and product evangelist, to kick off this year's event.  His experience has provided a perspective only someone who has dedicated his career to GIS can describe.

Come to hear Bern speak at 9:30 am on Wednesday, October 25 in Big Tex.

**Comment by pwblanton** [comment]
Esri has played a key role in the Texas GIS Forum beginning in 1987 when Jack Dangermond, the founder of Esri, was the keynote speaker. Every year since Esri has  supported the conference as a primary (or Platinum???) sponsor.

This year we're proud to welcome Bern Szukalski, Esri's well known and highly regarded technical and product evangelist, to kick off this year's event. His experiences provide a perspective only someone who has dedicated his career to GIS can describe.

Please come hear Bern speak at 9:30 am on Wednesday, October 25 in Big Tex.

**Comment by geochik** [comment]
@KCMack  Reviewed. Two thumbs up!

**Comment by KCMack** [comment]
Ok, maybe a slight different take to promote Esri's involvement and continued support through the  years...........  The intention is to focus on the relationship.

Esri has played a key role in the Texas GIS Forum beginning in 1987 when Jack Dangermond, the founder of Esri, was the keynote speaker. Every year since then Esri has actively participated in the Forum supporting not only the event, but the entire Texas GIS community.

Keep the rest the same.....................

**Comment by pwblanton** [comment]
Perfect!

**Comment by christoball** [comment]
@KCMack @pwblanton I've incorporated those edits:
https://preview.tnris.org/ellwood/8ade6d637cdd457dfbe5930225bd7c26106d1212/news/2017-09-20/technical-evangelist-technology-advocate-forum-keynote-bern-szulkaski/

**Comment by KCMack** [comment]
Terrific!  Thank you.

**Comment by christoball** [comment]
resolved in 8ade6d637cdd457dfbe5930225bd7c26106d1212

**Comment by KCMack** [comment]
Please correct the spelling of his name to Szukalski

**Comment by christoball** [comment]
fixed the name mispelling

**Comment by pwblanton** [comment]
Suggestions:
Chris, first paragraph, second sentence: add a comma after the word Forum.
Also, second paragraph, last sentence: spell out the word October.

**Comment by christoball** [comment]
resolved in aa076c106154da4ed0c03bca7c71accfc2f9854e
