### ISSUE TITLE
Add Sean Bio

### ISSUE THREAD

**Issue by christoball** [TNRIS/tnris.org#1416]
add here when available

**Comment by gmullins** [comment]
Sean is a Geospatial Scientist for Google’s Maps Customer Team. He has most recently been the technical lead for Google’s Enterprise Aerial Orthoimagery program, and designed the workflows for provisioning and serving terabytes of imagery at scale on Google Cloud Platform. Since joining Google in 2008, he has worked to bring analytic capabilities to the Google’s Geospatial platform and developed technologies to bring Google Earth and Maps to disconnected tactical and crisis-response environments. Prior to joining Google, Sean worked as a geospatial analyst in the Office of Counterterrorism and as a developer in the eGEOINT Management Office at NGA. He earned a bachelor's degree in geography from Virginia Tech in 2004, where he also earned his M.S. in geographic information science in 2005.

**Comment by gmullins** [comment]
I accidentally closed this.

**Comment by gmullins** [comment]
Ready for your review @KCMack

**Comment by christoball** [comment]
@gmullins @KCMack view preview here:
https://preview.tnris.org/ellwood/d4d4fffe362f0586b3b7aaf73dbca14d02be4a5d/texas-gis-forum/2017/agenda/#sean-wohltman

**Comment by gmullins** [comment]
Looks like we need to remove comma between ....program, and....
All the rest ok with me.

**Comment by christoball** [comment]
Is that it? @KCMack any edits?

**Comment by KCMack** [comment]
Looks good!  Thanks.

**Comment by christoball** [comment]
resolved in 5aa5652bdc45acece57f0008651d0f24583b1263
