### ISSUE TITLE
GeoRodeo Redirect

### ISSUE THREAD

**Issue by christoball** [TNRIS/tnris.org#1672]
Just noticed that the markdown for the 2019 GeoRodeo was created in the root of the GeoRodeo folder and not in its own 2019 folder. 

I am going to place the markdown in a 2019 folder, so we will need to change the redirect of the tnris.org/georodeo to point to tnris.org/georodeo/2019

**Comment by adambreznicky** [comment]
@christoball don't make that change.

we had infinite redirect issues related to this which is why we were forced to drop the redirects and change the structure to work out of the root of the georodeo folder. 

**from now on, the current georodeo page will be hosted from the root.**

when the next year comes around we will archive the old one into a year named subdirectory. this way, the current georodeo page is always located in the root
