### ISSUE TITLE
Font libraries for tnris.org

### ISSUE THREAD

**Issue by christoball** [TNRIS/tnris.org#1690]
This is a question I want to get sorted out towards the beginning. I'd like to be able to consider a variety of webfonts in the redesign of tnris.org

Can y'all please direct me to what libraries or methods for using alternative fonts that you feel will work best with the site so I know where I will be able to draw from.

**Comment by jwhaney** [comment]
Right now for data.tnris.org we use this mdc npm package (https://material.io/develop/web/components/typography/) which allows the use of all google fonts I believe, however, the base font is Roboto for material, which I think is the only one we use. I imagine we will continue with that on tnris.org. The typography package allows the use of other fonts if needed but since we are using material, and to maintain uniformity, we should probably stick to the free google fonts (https://fonts.google.com/).

Does that answer your question?

**Comment by christoball** [comment]
@jwhaney Yes, thank you, that helps a lot.

**Comment by jwhaney** [comment]
ok good deal, I'll go ahead and close this then.
