### ISSUE TITLE
GIS Community Meeting Invitation

### ISSUE THREAD

**Issue by geochik** [TNRIS/tnris.org#187]
@christoball 
I am unable to get into MailChimp b/c it is asking me to verify my computer with a password and I cannot get to the GIO mailbox. So, I need your help. I am requesting an updated 2nd Qtr GIS Community invitation. You can replicate the last campaign and make the changes there. I will change the information on the GIO page.
Please add the following text to the body of the invite:
_UPDATED LOCATION:
In light of the current health crisis, we have made the decision to host the 2nd Quarter GIS Community meeting virtually! We hope you can join this unprecedented event to get caught up on the latest project news and hear from guest presenter, 1Spatial. Click on the link (https://attendee.gotowebinar.com/register/3231973054519613710) to register now!_

I am working on the agenda and will send it to you shortly.

@gmullins @rwade2126 and myself will review the invite to finalize. This invitation must be ready to go out on Monday morning.

Thank you!

**Comment by christoball** [comment]
We should change the main photo since it shows a in person meeting.

Do you like any of these for a main image? The top one is pretty clean and straightforward and maybe in line with our style, but i also like the second one.

![image](https://user-images.githubusercontent.com/1877550/78941323-13ce2880-7a7d-11ea-9b30-6f29ab3aef8a.png)

![image](https://user-images.githubusercontent.com/1877550/78941349-1f215400-7a7d-11ea-89b1-55bc2b252350.png)

![image](https://user-images.githubusercontent.com/1877550/78941363-27798f00-7a7d-11ea-87d6-15e7e626b284.png)

**Comment by geochik** [comment]
@christoball 
Here is the agenda along with an abstract from the guest presenter. I don't have the full version of Acrobat so I can't merge the two. Can you please take care of that and add the agenda to the MailChimp invite? I want to hit send today so as soon as possible is much appreciated!
[GISComm_Agenda_20200430.pdf](https://github.com/TNRIS/tnris.org/files/4470844/GISComm_Agenda_20200430.pdf)
[TX_Abstract.pdf](https://github.com/TNRIS/tnris.org/files/4470845/TX_Abstract.pdf)

**Comment by christoball** [comment]
@geochik Ok, i've integrated these into the email draft, go have a look.

**Comment by christoball** [comment]
resolved, email sent
