### ISSUE TITLE
GIS Forum Training

### ISSUE THREAD

**Issue by mitchellryant** [TNRIS/tnris.org#1880]
A form has been submitted from: https://tnris.org/contact/

Form parameters
==================

form_id: contact
Reason: General Question or Comment
Question or Comments: Description for 2019 TX GIS Forum workshop "Using ArcGIS and Open Source" refers to "**Juniper Notebook**" .... should that actually be "**Jupyter Notebook**"?

Name: Roberto Anaya
Email: Roberto.Anaya@twdb.texas.gov
Phone: 5124636115
Organization: Texas Water Development Board
Address: 1700 N. Congress Ave.
Industry: Government
DateSubmitted: 2019-08-29

**Comment by KCMack** [comment]
Please change the spelling of Jupyter Notebook - the spreadsheet has been updated to reflect this change.

**Comment by christoball** [comment]
Updated it in current site and api
 
@KCMack preview here:
https://preview.tnris.org/ellwood/270bcdcd8730eb0a4601aca55035aeda3401d5c8/

**Comment by adambreznicky** [comment]
we have deployed the new tnris.org major update verison to production. the use of CSVs for training content management has gone live.
as per the new workflow, @KCMack please log into the api.tnris.org admin console and verify the change has been made as necessary. if it has, it should already be live on tnris.org. If you have any issues, please let us know. 

please respond to this thread to confirm that the change has been completed so that we can close this issue. thanks!!!!

**Comment by adambreznicky** [comment]
i see the change was made in the api.
closing issue.
thanks all
