### ISSUE TITLE
Copy Link URL for DataHub Images

### ISSUE THREAD

**Issue by christoball** [TNRIS/tnris.org#1886]
Can we add a copy link url button on DataHub Images?

This would be useful for incorporating them into articles or other places on the site.

**Comment by adambreznicky** [comment]
can you elaborate about what you mean? are you referring to the api admin console where you upload the images? 
i know i had added a copy link url button for the tnris.org images and docs tables in the admin console. are you imaging something similar for this?

**Comment by christoball** [comment]
@adambreznicky "i know i had added a copy link url button for the tnris.org images and docs tables in the admin console. are you imaging something similar for this?"

Yes, that's what I'm thinking. I figure it would make the most sense somewhere under a data collection editing, under the images. Possibly to the right of where the url shows up or below it.

![image](https://user-images.githubusercontent.com/1877550/64352418-9fe91080-cfc1-11e9-992c-e7d5d2828750.png)

**Comment by adambreznicky** [comment]
right on. that is indeed do-able but it is an enhancement to the backend api.tnris.org and not the website. any issues related to the admin console for the api should be created in the api.tnris.org repo. i'm going to close this issue since it is unrelated to the website. could you please go create the issue in the api.tnris.org repo? uploading your screen shot will help. thanks.
