### ISSUE TITLE
Rework Training Course layout

### ISSUE THREAD

**Issue by christoball** [TNRIS/tnris.org#196]
Per @geochik, we will rework the layout of the Training courses to be a little more visually interesting and move away from just a listing down the page.

Also add possible categories to help filter (beginners, intermediate, advanced)

**Comment by KCMack** [comment]
[Training Topic Categories_4.22.20.docx](https://github.com/TNRIS/tnris.org/files/4517936/Training.Topic.Categories_4.22.20.docx)

Try these

**Comment by christoball** [comment]
@KCMack thank you, so it looks like we have two main categories - **Basic** & **Beyond Basics**?

**Comment by KCMack** [comment]
YES, and yet the sub categories are important, too if we're going to provide understandable categories.  To be helpful for those looking for more help, the two categories need to include subcategories to be effective.

**Comment by jwhaney** [comment]
something to make sure and consider regarding this issue @christoball , currently there are no categories associated with education/training records coming from the api i don't think. that means a backend change to the model and forms in order to add a domain. also, the frontend tnris.org javascript handles getting the training records form the api and displaying them. there is some fairly complex logic that you will have to dive into to "rework the layout of the Training courses to be a little more visually interesting and move away from just a listing down the page".

**Comment by adambreznicky** [comment]
resolved via commit 6bff8f142b45806fadfaf72d2afe24c453874155
