### ISSUE TITLE
Google bot crawl errors

### ISSUE THREAD

**Issue by jseppi** [TNRIS/tnris.org#211]
Google finding lots of 404s. Look into it.

![image](https://cloud.githubusercontent.com/assets/697848/6431203/c511efe6-bfed-11e4-9a30-21a764f2253a.png)

**Comment by jseppi** [comment]
Actually I don't think this is from the sitemap. It looks to me like Google isn't handling the `base` element properly, so it tries to follow each link _relatively_ on each page. This is probably not good.

**Comment by jseppi** [comment]
Ok, the RFC for the `base` tag specifies that the href needs to be _absolute_. So, even though Chrome and Firefox seem to cope with the relative URIs we are using, I am guessing the google bot does not.

I think the solution is to use `<base href="//tnris.org" />` in production, and use the relative URIs on drax-hosted test deployments.

/cc @wilsaj

**Comment by wilsaj** [comment]
The HTML5 spec does allow relative base hrefs: http://www.w3.org/TR/html5/document-metadata#the-base-element but if Googlebot is choking, then it's def a problem. Relative base hrefs are also not supported in IE9 and there is a janky dance going on to deal with that.

I'll try making all links explicitly relative, since that solves both problems and doesn't add any extra steps to deployments. I really want keep deployment steps as simple as possible since failure at that point means :fire: :fire_engine: :scream_cat: .
