### ISSUE TITLE
Update AL\LP Map to AGO

### ISSUE THREAD

**Issue by ghost** [TNRIS/tnris.org#243]
I talked to @LaurenKirk and we both think it is a good idea to move the AP\LP maps from Carto to AGO. This will give editors a ease of use and greater update capabilities. Below are the embed links to the maps. Height and Width can be adjusted. Ultimately I think it would better to move all the maps on the site (4 in total) to AGO, and to have @e00o be the principle styler of the maps.

These two maps recreate the carto maps, but I am not very fond of the Orange. 

Address Points: https://tnris.org/stratmap/address-points/

`<style>.embed-container {position: relative; padding-bottom: 80%; height: 0; max-width: 100%;} .embed-container iframe, .embed-container object, .embed-container iframe{position: absolute; top: 0; left: 0; width: 100%; height: 100%;} small{position: absolute; z-index: 40; bottom: 0; margin-bottom: -15px;}</style><div class="embed-container"><iframe width="500" height="400" frameborder="0" scrolling="no" marginheight="0" marginwidth="0" title="Address Points Map" src="//tnris.maps.arcgis.com/apps/Embed/index.html?webmap=e8c2c6bd86064f6fbadbd38a60b50ccd&extent=-116.3038,23.2551,-83.8502,38.7487&home=true&zoom=true&previewImage=false&scale=true&search=true&searchextent=true&disable_scroll=true&theme=light"></iframe></div>`

Parcel Map: https://tnris.org/stratmap/land-parcels/

`<style>.embed-container {position: relative; padding-bottom: 80%; height: 0; max-width: 100%;} .embed-container iframe, .embed-container object, .embed-container iframe{position: absolute; top: 0; left: 0; width: 100%; height: 100%;} small{position: absolute; z-index: 40; bottom: 0; margin-bottom: -15px;}</style><div class="embed-container"><iframe width="500" height="400" frameborder="0" scrolling="no" marginheight="0" marginwidth="0" title="Land Parcels Map" src="//tnris.maps.arcgis.com/apps/Embed/index.html?webmap=7f5626b267a042a7869926b3d379f5b9&extent=-116.3038,23.2551,-83.8502,38.7487&home=true&zoom=true&previewImage=false&scale=true&search=true&searchextent=true&disable_scroll=true&theme=light"></iframe></div>`

**Comment by JasonKleinert** [comment]
@mitchellryant, are the above mentioned AGOL maps ready to go on the site or are we waiting for input/approval from @e00o or @LaurenKirk?

**Comment by ghost** [comment]
@JasonKleinert lets wait for @e00o to look over them. I just re-created the maps in carto. he might not change anything.

**Comment by jwhaney** [comment]
@LaurenKirk , @mitchellryant 
There is currently no SOURCE field for the data in this new coverage map so I have edited the text that currently shows above the map:

__original__
"The map below shows available address points across Texas. Data were received from across 247 counties and may not be complete coverage. Please see the SOURCE field on each record to determine the data creator or aggregator. Use the DataHub to download."

__edited__
"The map below shows available address points across Texas. Data were received across 247 counties and may not be complete coverage."

I also removed the redundant datahub link since there is a big Data Hub button below the map where the user can go to download the datasets.

Please let me know if there are any issues with this change.

**Comment by jwhaney** [comment]
@e00o , @LaurenKirk , @mitchellryant 
fyi, previews will be here in a few minutes when i push to develop:

land parcels - http://develop.tnris.org/stratmap/land-parcels/
address points - http://develop.tnris.org/stratmap/address-points/

**Comment by LaurenKirk** [comment]
@jwhaney @mitchellryant 

John, thanks for fixing that inconsistency.  The previews look good.  Not sure if @e00o  tweaked them or not.
