### ISSUE TITLE
Replace content on front page

### ISSUE THREAD

**Issue by KCMack** [TNRIS/tnris.org#250]
**From:** 
GIS Education & Training
2020 Training Courses
Advance your professional GIS skills by taking our affordable courses.

Working from home is the new normal environment and to accommodate your training needs, TNRIS has changed the delivery of training.

In collaboration with our training partners the new schedule includes:

Instructor-led online classes to offer the same benefits of having your instructor in the session with you
Self-paced online courses
Check out the courses listed on the Education page and register now to take online courses this summer.

**To:** 
GIS Education 
New Fiscal Year Course Listing
Continue to advance your professional GIS skills by taking our affordable courses.

Working from home is perfect to participate in online training. 

In collaboration with our training partners the schedule includes:

* Instructor-led online classes with your instructor in the session with you
* Self-paced online courses

Check out the courses listed through December on the Education page and register now.

**Comment by KCMack** [comment]
@ctrepka - would be ideal to have this change made by the end of next week.

**Comment by ctrepka** [comment]
Sure thing, I'll jump on it today or Tuesday.

**Comment by geochik** [comment]
Edited - @KCMack I took out the bullets since there were only two and combined the first two sentences with slight text modification.

To:
GIS Education
New Fiscal Year Course Listing

Working from home is ideal for online training! Continue to advance your professional GIS skills by taking our affordable courses.

In collaboration with our training partners, the schedule includes live instructor-led online classes and for the independent learner, self-paced online courses.

Check out the courses listed through December on the Education page and register now.

**Comment by KCMack** [comment]
Looks good.  Thanks
