### ISSUE TITLE
StratMap Contracts page enhancement/content changes

### ISSUE THREAD

**Issue by jwhaney** [TNRIS/tnris.org#263]
Plans to change content and maybe make some enhancements to the StratMap contracts page. More information and details to follow.

https://tnris.org/stratmap/stratmap-contracts/

**Comment by jwhaney** [comment]
__Notes from StratMap Contracts page 10/13/20 meeting__:

- biggest change to this page is to the vendors section
  - all vendors now expired
  - still going to have pool of vendors moving forward; some of the same companies and some new
    - online excel document link will be provided by @gmullins with all information for each vendor
    - will need to find most recent logo for each vendor if we don't already have it
  - will be more vendors this time - from 15 up to possibly 40
    - will likely be re-organizing the vendor section to take up full width of page and put vendors in a list format or maybe smaller card due to the increased number
  - icon with link to home page is not needed; change to link behind company logo
  - link to vendor contract page and link to DIR vendor contract page needed
  - possible enhancement to add a filtering mechanism to filter vendors based on category (software, products, services)
- will also need to remove some text, etc on the page - more details will be provided via an online word document link by @gmullins

**Comment by ghost** [comment]
@jwhaney These are great notes! I attached the Word doc (reviewed by FR). I also attached a word cloud I've used many times in presentations about the SM Contracts that I thought could also go 'somewhere' on the page. It's a smattering of the available products and services. 
[SM Contracts - Webpage update.docx](https://github.com/TNRIS/tnris.org/files/5380779/SM.Contracts.-.Webpage.update.docx)
![Cloud 1 (2)](https://user-images.githubusercontent.com/4921113/96043268-4c87f980-0e34-11eb-9594-f2d4d52f9f86.png)

**Comment by ghost** [comment]
@jwhaney The list of vendors is here. ~ (edited: removed link after talking to @geochik. shouldn't be publicly accessible)

The ones with a checkmark under the Complete field are ready to go on the webpage, meaning they are active contracts people can use today.

**Comment by geochik** [comment]
Just a quick note. Esri's contract is valid until Feb 1, 2021 and RazorTek until Oct 21, 2020. So technically not all contracts are expired.

**Comment by ghost** [comment]
Thanks @geochik ! I think RazorTek's is too close to expiration to keep on the site, but we should definitely keep on Esri's until we have their new contract info.

**Comment by Ldsmiths** [comment]
@gmullins @geochik I've made good progress on these changes, I just have a few questions for clarification:

1. ) I removed the word “Vendor” from the hyperlinked text

	ex.)
	Vendor Contract Page --> Contract Page
	DIR Vendor Contract Page --> DIR Contract Page

This allows the cards to be smaller and fit more cleanly on the page. I’m thinking since they’re all under the “Vendor Pool”, it can be implied that the links are to the vendor contract pages. Will this be okay or should I make sure "Vendor" is included? 

![image](https://user-images.githubusercontent.com/70979203/96160778-07b79d80-0edc-11eb-8cb4-ef0a5f32c71b.png)


2. ) Surdex has the same URL for Contract Page and DIR Contract Page in the Excel doc. Is this correct?

3. ) Should the header that currently reads “Vendors 2016 - 2020” be updated to "2020 – 20xx"? Should it just say Vendors?

4. ) Should this text from the bottom of the page _“Note: On the DIR pages, the original RFO is labeled as "Geographic Information Systems (GIS) Hardware, Software, and Services."_ still be included?

5. ) We could update the banner image to include the Texas Word Cloud image

![image](https://user-images.githubusercontent.com/70979203/96161397-dab7ba80-0edc-11eb-9567-7924230a7167.png)

Or we could put it to the side with the DIR logo. What do you think?

**Comment by geochik** [comment]
Looks like you are already aware that we cannot include those companies on the new contracts page until they have a completed contract. So thank you! Here are my responses:

1) The "vendors" have often commented they don't like that word so I am good with that!
2) Not sure but that should be fine.
3) I think it should just say, "Pre-Qualified Companies" or something of that nature.
4) Yes
5) I love the Word Cloud. Could you make the "aura" stand out a little more? Or maybe it's just the size of the thumbnail. I bet it will look better on the page.

Also, @gmullins has complete override authority on my responses!!

**Comment by ghost** [comment]
@geochik LOL on authority. 

1. Agreed. No to the word "vendor"
2. My bad! The Excel sheet is now updated for Surdex.
3. How about "Pre-Qualified Geospatial Providers"
4. Yes, and has been updated to: Note: On the DIR pages, the original RFO is labeled as "Geographic Information Systems (GIS) Hardware, Software, and Services and Information Technology (IT) Based Surveying Hardware, Software and Related Services."
5. Yes, I like the word cloud as the banner, reserving the other StratMap graphic for the StratMap Main Page only.

Thanks! @Ldsmiths
