### ISSUE TITLE
TNRIS.org Land Parcel/Address Point announcement

### ISSUE THREAD

**Issue by LaurenKirk** [TNRIS/tnris.org#290]
@geochik @gmullins @pwblanton 

Morning y'all.  Gayla reminded me of a conversation we had not too long ago about posting an announcement on the land parcel and address point project pages on tnris.org (and probably DataHub too) about the delayed release of the 2020 land parcel and address point datasets.  My plan is to offer 2020 data by customer request only; once everything I can get my hands on for 2020 has come in and been standardized, I'll make it all available for mass access and download via DataHub.  I've listed the announcement below.

"Thank you for your interest in TNRIS' Land Parcel and Address Point datasets.  Due to unexpected circumstances our annual 2020 statewide refresh of both our Land Parcel and Address Point datasets have been delayed.  If you are interested in obtaining updated 2020 data, please use the "Contact" tab located on the respective 2019 Land Parcel and Address Point project pages on our DataHub website.  Please note, full statewide coverage is not available and not all requests may be able to be fulfilled.

Production of TNRIS' 2021 Land Parcel and Address Point datasets has not been affected.  Currently, TNRIS anticipates a mid to late Summer 2021 release for the annual 2021 refresh.

We invite you to use the Contact tab on both project pages for any questions you may have."

Let me know what y'all think!  I'll pull IS on to this thread after any changes are made.

**Comment by geochik** [comment]
@LaurenKirk great writeup! I made a few edits and added hyperlinks to the datasets. Take what you like, throw away the rest.

Thank you for your interest in TNRIS' Land Parcel and Address Point datasets. Due to unexpected circumstances, our annual 2020 statewide refresh of both Land Parcel and Address Point datasets have been delayed. If you are interested in obtaining 2020 data, please use the "Contact" tab located on the respective 2019 [Land Parcel ](https://data.tnris.org/collection/2679b514-bb7b-409f-97f3-ee3879f34448)and [Address Point](https://data.tnris.org/collection/117cf9e1-3b1e-48f2-97a3-47020d871035) project pages on our DataHub website. **Please note data may not be available for all counties.**
The production timeline for 2021 Land Parcel and Address Point datasets has not been affected. Currently, TNRIS anticipates a mid to late Summer 2021 release for the annual refresh.
We invite you to use the Contact tab located on the respective DataHub project pages for any questions you may have.

**Comment by pwblanton** [comment]
This is perfect, Felicia!

**Comment by ghost** [comment]
@LaurenKirk Awesome! I noticed Land Parcel and Address Point instead of the plural versions. I think they should be changed site-wide, on the data pages and the project pages, if you want to make that change. Otherwise, I pluralized them in this version I took from @geochik What do you think about the Available Datasets maps on each page? May be a separate issue or discussion. Oooh. How about each county is colored based on data availability? Ex. 2019 = color 1, 2020 = color 2, 2019 & 2020 = color 3. Erik would be good to consult on this. 

"Thank you for your interest in TNRIS' Land Parcels and Address Points datasets. Due to unexpected circumstances, our annual 2020 statewide refresh of both the Land Parcels and Address Points datasets have been delayed. If you are interested in obtaining 2020 data, please use the "Contact" tab located on the respective 2019 [Land Parcels](https://data.tnris.org/collection/2679b514-bb7b-409f-97f3-ee3879f34448) and [Address Points](https://data.tnris.org/collection/117cf9e1-3b1e-48f2-97a3-47020d871035) DataHub pages on our website. 
**Please note data may not be available for all counties.**
The production timeline for the 2021 Land Parcels and Address Points datasets has not been affected. Currently, TNRIS anticipates a mid to late Summer 2021 release for the annual refresh.
We invite you to use the Contact tab located on the respective DataHub project pages for any questions you may have.

**Comment by LaurenKirk** [comment]
@gmullins @geochik @pwblanton 

Ahh thank you ladies for your input, always saving me from silly grammatical errors!!  @gmullins I think symbolizing the availability maps on the project pages by year is a great idea! Will def freshen up the look of the maps on tnris.org; I'll get with Erik today.

Thanks again for your help!!
