### ISSUE TITLE
Forum Image on Carousel

### ISSUE THREAD

**Issue by geochik** [TNRIS/tnris.org#405]
@rachel-longoria It was brought to my attention that the image on the front page carousel is being cut off. I checked both Chrome and Safari and it is doing it on both. Any idea what could be going on here? Here is my screenshot:
![Screen Shot 2022-01-12 at 1 46 39 PM](https://user-images.githubusercontent.com/7750220/149214760-1c7bf2e2-221c-487c-beaa-ecfaceb165c3.png)

**Comment by space-longoria** [comment]
@geochik This is happening because the image is inside the carousel, so each image in the carousel is that same width and height. To fix the padding issue, I would have to edit the carousel to span the entire top part of the webpage, which would change how all the other images appear as well. I can look into this if it's something you'd like to do

**Comment by geochik** [comment]
Oh dear. Okay. I think it looks a little sloppy so I would say if we can't fix it easily, we should take it down until we can recreate the graphic to match the size of the others. If you can provide me with the image size, I'll ask CMP to create it.
I was also wondering about the text that shows up on each image. I don't recall seeing that before and it looks like it obstructs the text on the graphic. Is there a way to keep that txt from showing up on the image?
