### ISSUE TITLE
Allow plain HTML content items

### ISSUE THREAD

**Issue by jseppi** [TNRIS/tnris.org#43]
Perhaps the markdown conversion step should ignore pure html content files. Any file that already has a `.html` extension could just be passed-through without the conversion step. The frontmatter section should still be used.
This is similar to what harp.js does. 

It would probably make html-heavy news items such as `new-smith-county-imagery-available` easier to write/deal with/maintain.

**Comment by wilsaj** [comment]
I agree that it would be a little cleaner to have untouched `.html` content files as an option. I took a serious look at implementing this and I'm decidedly :-1: on this (sorry!). It would add more complexity to the build pipeline than I think is worth it. html elements already get passed through the markdown parser unscathed, so if a `.md` markdown file only contains html content then the output should be the same either way. Since text editors don't seem to handle the html-in-markdown case very well, I would instead recommend that for larger pages where the content block is going to be entirely html, just use a content-less markdown files that reference a separate template. This is *almost* as good with the only downside being you have to use two files instead of one, which seems relatively minor. For example this is how the frontpage works: [index.md](https://raw.githubusercontent.com/TNRIS/tnris.org/master/content/markdown/index.md) and [index.html](https://github.com/TNRIS/tnris.org/blob/master/templates/index.html)

**Comment by jseppi** [comment]
Ok, that sounds reasonable.
