### ISSUE TITLE
Better description on Order Form

### ISSUE THREAD

**Issue by mitchellryant** [TNRIS/tnris.org#568]
The description on the order form needs to be improved. @christoball 

Maybe mention the following.
1. Customer gets quote before any.
2. explanation of fees and services.
3. turn around time
etc

**Comment by ThorTheDestroyer** [comment]
This will all be taken care of with the upcoming pricing sheet being published on the site.  I think it is self explanatory that they won't pay for anything until they want to proceed since we don't ask them for any payment info. Turn around time of 3-10 business days can be added to the top of the form

**Comment by mitchellryant** [comment]
People are still using the data support form to request data, and on almost all for them the for a quote before proceeding. It would not hurt to mention it.   It should say more than this.

"Welcome to the Map Service Center's order form.
Please fill out the information below and TNRIS staff will begin processing your order as soon as it is received.

For other inquiries please use the general contact form."

**Comment by ThorTheDestroyer** [comment]
pull request created for orderform with quote and turn around time language added.

**Comment by christoball** [comment]
resolved in #570

**Comment by mitchellryant** [comment]
Could you replace the text at the top with this? 

Please fill out the following form to receive a quote for your data request.  Once you receive your quote and any adjustments are made, TNRIS staff will contact you for payment information. Typical turnaround time for quotes is 3-10 business days.

**Comment by ThorTheDestroyer** [comment]
naw, i like it the way it is.  That one sounds like it is for someone obsessed with quotes. Our turnaround time for quotes is usually 1 business day. Turn around time for delivery is 3-10 days.  I've rearranged the language so that the quote is mentioned first and laguage related to turnaround time has been updated.

**Comment by mitchellryant** [comment]
Ok whatever, you are right it is a great run on sentence, that is confusing. lets keep it.

**Comment by ThorTheDestroyer** [comment]
alright, i updated it.  made sure to say quote at least 3 times.
