### ISSUE TITLE
new header elements -- need to adjust breakpoint for mobile

### ISSUE THREAD

**Issue by jwhaney** [TNRIS/tnris.org#6]
__less than 992px wide and greater than 767px wide__

within this pixel width range the new additions to the header (>Events and Geographic Information Office) cause the header to double up in height. see below photo. need to alter breakpoint so all header elements collapse into mobile hamburger menu.

![image](https://user-images.githubusercontent.com/13525011/63377347-93c04a80-c355-11e9-8f77-419044ea6998.png)

**Comment by adambreznicky** [comment]
just reviewed. looks good. responsiveness is behaving as expected. i dig.

a few consistency updates before going live:

1. the header option within the Programs dropdown "Lidar" should be "Elevation - Lidar" to match the stratmap sub-navbar, footer, page url, and page title
2. "StratMap Contracts" should become just "Contracts" in the page url, page title, and stratmap sub-navbar in order to be consistent with the header dropdown and footer links. I suggest making these just 'Contracts' opposed to adjusting the opposite and making the header/footer "Stratmap Contracts" because putting the label stratmap in front is redundant. No other stratmap page has the label stratmap in front of it and every stratmap page already has "StratMap" in the title on a line above the page name/title. Even the URL is /stratmap/stratmap-contracts with the redundant stratmap label where the other pages are not.
3. Rearrange the order of the footer links under "Data & Maps" to match the new order used in the header
4. "Education" in the Programs dropdown should be "Education and Training" to consistently match the title on the actual education page. Swap "&" in the footer link with "and" to match as well.
5. Education page sub-navbar labels the purchasers page as "For Purchasing Agents" where it should be updated to be "Purchaser Resources" like the footer link and page title.

**Comment by christoball** [comment]
@adambreznicky I believe I've addressed the inconsistencies, preview here:
https://beta.tnris.org/

**Comment by adambreznicky** [comment]
awesome buddy! looks great to me!
