### ISSUE TITLE
Data Catalog Remove columns

### ISSUE THREAD

**Issue by mitchellryant** [TNRIS/tnris.org#673]
I would like to remove the following columns from the data catalog.

download_lvl - not being used
relationship_tag - not being used
thumb - not being used
agency - add information to long description
agency_web - add information to long description
agency_gis_page - add information to long description
tnris_hosted - add information to long description

@jseppi @wilsaj @christoball thoughts?

**Comment by wilsaj** [comment]
Only change I'd suggest is to keep agency as a short code since we'll probably want that for filtering and it can be good info to display in the catalog page table. I'd also suggest renaming to `'organization'` since we want to catalog data from things that aren't exactly state and federal agencies, like county governments and Councils of Governments. `tnris_hosted` would then be implied when `organization == 'TNRIS'`.  Associated data like web page and GIS page don't need to be repeated for every row - there should be a single internal source of that info.

**Comment by christoball** [comment]
Ok with removing download_lvl, relationship_tag, and thumb.

But, my idea for the agency stuff/tnris_hosted is that those will be easier to call in where needed. The long description isn't the only place where I foresee placing those.

All of those are intended for easier filtering and labeling which we hope to implement as we improve.

**Comment by mitchellryant** [comment]
I want to make sure we are using the fields we have. How does agency differ from source, is the data is normalized? Does the user care what dataset are hosted at tnris if they can download them from the catalog entry?

**Comment by wilsaj** [comment]
There are a handful of places where source contains additional division info. For example `USGS (National Mapping, Biological Resources, and Water Resources Divisions)`, but I reckon we could just reduce that to USGS and put that division info into the long description.

**Comment by mitchellryant** [comment]
Based on workload, any large scale improvements to the data catalog will not happen till after the release of the new water plan application, April. At that point a complete overhaul  or re-imagining may be in order.

**Comment by mitchellryant** [comment]
meeting to discuss all options has been set for Monday at 2pm.
