### ISSUE TITLE
Platinum Sponsor Demo Descriptions

### ISSUE THREAD

**Issue by christoball** [TNRIS/tnris.org#68]
We still don't have which sponsor is doing which day and a description. 

@KCMack are those available yet? I'll also need them for the printed program.

**Comment by KCMack** [comment]
Wednesday - Esri tech talk
Presenter: Paul Ross
Platinum Sponsor Presentation
Using ArcGIS to Tell Human Stories
For centuries people have been telling stories and communicating with maps.  Today, WebGIS makes it fast and easy to create and share important information and stories locally or even worldwide.  In this session, Paul will discuss how new tools like StoryMaps, Dashboards and app-building products combine with SaaS to create new and exciting ways to create information products and share them.

Paul is a Sr. Product Manager on the ArcGIS Online team working at Esri World Headquarters in Redlands, California.  At Esri, Paul has focused on emerging Internet/SaaS services as well as navigation and logistics products.  In his current position Paul is working to develop new SaaS-based products, services and content including the integration with desktop, mobile, server and web-based products.  Prior to coming to Esri in 2007 Paul worked for MapQuest.com as well as a regional Internet Service provider. linkedin.com/in/paulross01

**Comment by KCMack** [comment]
Thursday Sponsor Presentation - AppGeo
Title: What's Driving Your Data?
Co-Presenters: Kate Hickey and Morgen Healy

Summary:
Organizations are spending more time and money than ever on data, data science, and
analytics. There is no question that data platforms are increasingly powerful and are a key
ingredient to success. But organizations are making far more progress on the technological
front of data use than the human one. Organizations want to leverage their data to make better
decisions and improve outcomes, but in order to achieve this they also need to consider
organizational realities, which is where the complexities lie. In this talk we will discuss various
approaches and strategies for leveraging data (geospatial or otherwise) within your
organization.

Morgen Healy’s Bio:
Morgen Healy has been working as a GIS professional for nearly 17 years, and much of that
time has been with AppGeo. She is based primarily in AppGeo's Boston office with frequent
trips to the Austin location. She leads a wide range of GIS projects, including State and Federal
transportation projects, strategic planning, enterprise GIS architecture, and website design and
development projects. In her mind, October is the perfect month. If you're lucky, and if the New
England weather cooperates - you can still water ski at the beginning (in a wet suit), downhill ski
at the end (yes, snow on Halloween is a thing in the northeast) and attend the Texas GIS Forum --
all in one month!
Kate Hickey’s Bio:
Kate is a Vice President at AppGeo, leading the consulting services and customer support
teams. She's been with the company for over 18 years and loves the intellectually challenging
and dynamic culture of the place. She manages a broad range of geospatial projects including
the design and build of custom applications, performing analytics, and focusing on her true
passion -- strategic planning and understanding organizational behavior. She loves coming to
Austin and the Texas GIS Forum for the great ideas, stimulating conversation, company, and of
course - the tacos and barbecue.
