### ISSUE TITLE
Remove 'entry' from data catalog urls?

### ISSUE THREAD

**Issue by christoball** [TNRIS/tnris.org#735]
Is there a reason to have 'entry' as part of the urls for the data catalog?

It seems to go against our idea of simplifying things by taking out the categories from the url.

Also, if there's no 'entry' page, then they aren't really sub-pages of 'entry'.

Thoughts? @wilsaj @mitchellryant

**Comment by wilsaj** [comment]
The main reason is to leave room for other types of things besides entries. Like collections or other views on the catalog. If we pull everything directly under `data-catalog/` then it won't be possible to undo that. This is a common way of organizing urls.

Reason we removed categories from the url wasn't to shorten them, but because categories are subject to change as things get reorganized and this would break links and require moving images around and all of that.
